name = 'KouOrganize'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Theme to organize your articles'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/Kou-Reo/Hugo.KouOrganize'

# If you have a running demo of the theme
demosite = 'https://koureo.com/'

# Taxonomy terms
tags = ['Archive', 'Docs', "Portfolio", "Personal", "Responsive"]
features = ['Responsive design', 'Table of Contents', 'Documentation sidebar menu']

# If the theme has a single author
[author]
  name = 'Kou Reo'
  homepage = 'https://koureo.com/'
